.py and .pyc :
    .py file is a python file which is generated by the user and inside that
        we can write a code in human language.  
    .pyc file is a python byte compile file. Which use to compile the code of
        python file.
    When python (.py) file runs it will compile the code in .pyc file.
    So when we have a large module we can create a .pyc file to make execution
        faster.
    Evertime when our .py file runs in backend compiler generate .pyc file.

    